### ISSUE TITLE
Not fully POSIX

### ISSUE THREAD

**Issue by StruBE-KAUST** [StruBE-KAUST/ContaMiner#1]
shellcheck gives a lot of non POSIX issues.

**Comment by dunatotatos** [comment]
dev branch is now fully POSIX
commit 015d3de5948e8014a4f7ed8db978bb09b35db71b

**Comment by StruBE-KAUST** [comment]
dev branch is now fully POSIX
commit 015d3de5948e8014a4f7ed8db978bb09b35db71b

**Comment by StruBE-KAUST** [comment]
Will be merged for next release.
