### ISSUE TITLE
Can't get ContaMiner to work

### ISSUE THREAD

**Issue by mingyue80** [StruBE-KAUST/ContaMiner#13]
I'm running CentOS, was trying to access the webserver previously but that didn't work.  So I went ahead and installed the script.  Installed without issues, but then gave this persistent error:

Submitting job to SLURM... /usr/local/ContaMiner-master/scripts/solve.sh: line 149: sbatch: command not found
[FAILED]

Please advise, thank you.

**Comment by dunatotatos** [comment]
ContaMiner needs to run on a cluster, with SLURM available. It won't run on a laptop or a simple workstation.

Looks like the web server needs proper maintenance. It will be back in a few weeks.
